<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rplidar">

<!-- RP LIDAR A2 macro -->
<!-- Created by Stefan -->
<!-- Service Robotics Group Bulgaria - Version 1.0 from Oct. 5th, 2018. -->


<xacro:macro name="rplidar_a2" params="parent x_loc y_loc z_loc mesh_offset_X mesh_offset_Y mesh_offset_Z">


    <joint name="rplidar_a2_joint" type="fixed">
      <!--<origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />-->
      <!--Working parameters set for the static_transform_publisher -->
      <!--<node pkg="tf2_ros" type="static_transform_publisher" name="base_link_to_laser" args="0.1876 0 0.178 0 3.14159 3.14159   /base_link /laser"/>-->

      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 ${ROTATE_180_DEGREES} ${ROTATE_180_DEGREES}" />
      <parent link="${parent}"/>

      <!--This link represents the laser beam plane and orientation-->
      <!--Cahnge the name to laser as this name is used in the navigation stack-->
      <!--<child link="rplidar_laser_beam_plane" />-->

      <child link="laser" />
      
    </joint>


  <!--<joint name="rplidar_joint" type="fixed">
    <origin xyz="${round_plate_radius-rplidar_diameter/2-0.01} 0 ${round_plate_height+rplidar_height_of_laser_beam_plane}" rpy="0 0 0" />
    <parent link="second_deck"/>
    <child link="rplidar_laser_beam_plane"/>
  </joint>-->

  <!-- rplidar Laser -->
  <!--<link name="rplidar_laser_beam_plane">-->
  <link name="laser">
      <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.01" radius="0.2"/>
      </geometry>
      <material name="green" />
    </collision>

    <visual>
    <!--Looks like the rplidar mesh is not with the correct diameter, modifying the Y offset in order to show the visual "almost" correctly -->
      <!--<origin xyz="${mesh_offset_X} ${mesh_offset_Y} ${mesh_offset_Z}" rpy="0 0 0" />-->
      <origin xyz="${mesh_offset_X} ${mesh_offset_Y} ${mesh_offset_Z}" rpy="0 0 0" />
      <geometry>
        <!--<mesh filename="package://robot_description/meshes/rplidar-a2m4.stl" scale="0.001 0.001 0.001" />-->
        <mesh filename="package://robot_description/meshes/rplidar_a2/RPlidar_A2.stl.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="red" />      
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>

  <!--<joint name="laser_joint" type="fixed">
    <origin xyz="0.20 0 ${round_plate_height}" rpy="0 0 0" />
    <parent link="second_deck" />
    <child link="laser_visual" />
  </joint>

  <link name="laser_visual">
    <visual>
      <geometry>
     <mesh filename="package://robot_description/meshes/rplidar_a2/RPlidar_A2.stl.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="green" />
    </visual>
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>-->



  </xacro:macro>

</robot>
