
controller_list:
 - name: mover4_arm
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - Joint0
     - Joint1
     - Joint2
     - Joint3

#  - name: cpr_mover
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - Joint0
#      - Joint1
#      - Joint2
#      - Joint3
# # dobaveno ot men:
 - name: mover4_gripper
   action_ns: gripper_command
   type: GripperCommand
   default: true
   joints:
      - Gripper1
      - Gripper2

# - name: mover4_arm/follow_joint_trajectory
#   action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - Joint0
#      - Joint1
#      - Joint2
#      - Joint3      

