<?xml version="1.0"?>
<robot name="macros" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Body and kinect mount macros for Robco robot URDF.XACRO's -->
<!-- Created by Stefan -->
<!-- Service Robotics Group Bulgaria - Version 1.0 from Oct. 1th, 2018. -->

<!--###################### ROBCO STANDOFFS #######################################################################-->

  <xacro:macro name="robco_standoff" params="parent subname number lenght x_loc y_loc z_loc">
    <joint name="standoff_${subname}_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc+lenght/2}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_${subname}_${number}_link" />
    </joint>

    <link name="standoff_${subname}_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <cylinder length="${lenght}" radius="0.011113"/>
          <!--<mesh filename="package://robot_description/meshes/68-02421-8000-RA_Eddiebot_F-F_Standoff.dae" scale="${SCALE_mm_to_m} ${SCALE_mm_to_m} ${SCALE_mm_to_m}"/>-->
        </geometry>
        <material name="silver"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${lenght}" radius="0.011113"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="robco_standoff_first_second_deck" params="parent number lenght x_loc y_loc z_loc">
    <joint name="standoff_first_second_deck_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc+lenght/2}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_first_second_deck_${number}_link" />
    </joint>

    <link name="standoff_first_second_deck_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <cylinder length="${lenght}" radius="0.011113"/>
          <!--<mesh filename="package://robot_description/meshes/68-02421-8000-RA_Eddiebot_F-F_Standoff.dae" scale="${SCALE_mm_to_m} ${SCALE_mm_to_m} ${SCALE_mm_to_m}"/>-->
        </geometry>
        <material name="silver"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${lenght}" radius="0.011113"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="robco_standoff_second_third_deck" params="parent number lenght x_loc y_loc z_loc">
    <joint name="standoff_second_third_deck_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc+lenght/2}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_second_third_deck_${number}_link" />
    </joint>

    <link name="standoff_second_third_deck_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <cylinder length="${lenght}" radius="0.011113"/>
          <!--<mesh filename="package://robot_description/meshes/68-02421-8000-RA_Eddiebot_F-F_Standoff.dae" scale="${SCALE_mm_to_m} ${SCALE_mm_to_m} ${SCALE_mm_to_m}"/>-->
        </geometry>
        <material name="silver"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${lenght}" radius="0.011113"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>


  <xacro:macro name="robco_standoff_kinect" params="parent number x_loc y_loc z_loc">
    <joint name="standoff_kinect_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_kinect_${number}_link" />
    </joint>

    <link name="standoff_kinect_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robot_description/meshes/68-04556-RA_Kinect_Standoff_Assy.dae" scale="${SCALE_mm_to_m} ${SCALE_mm_to_m} ${SCALE_mm_to_m}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.008585" radius="0.001111"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>



<xacro:macro name="robco_kinect_support_plate" params="parent lenght width height x_loc y_loc z_loc">
    <joint name="kinect_support_plate_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="kinect_support_plate_link" />
    </joint>

    <link name="kinect_support_plate_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
        <box size="${lenght} ${width} ${height}"/>
          <!--<mesh filename="package://robot_description/meshes/68-02421-8000-RA_Eddiebot_F-F_Standoff.dae" scale="${SCALE_mm_to_m} ${SCALE_mm_to_m} ${SCALE_mm_to_m}"/>-->
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="${lenght} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>




<xacro:macro name="robco_mountpoint_visualizer_box" params="parent device_name lenght width height x_loc y_loc z_loc">
    <joint name="${device_name}_mount_point_visualizer_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="${device_name}_mount_point_visualizer_link" />
    </joint>

    <link name="${device_name}_mount_point_visualizer_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
        <box size="${lenght} ${width} ${height}"/>
          <!--<mesh filename="package://robot_description/meshes/68-02421-8000-RA_Eddiebot_F-F_Standoff.dae" scale="${SCALE_mm_to_m} ${SCALE_mm_to_m} ${SCALE_mm_to_m}"/>-->
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="${lenght} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>
 
 
</robot>