<?xml version="1.0"?>
<robot name="robco_hardware" xmlns:xacro="http://www.ros.org/wiki/xacro">


<!-- macro for 2WD base containing the drivetrain, battery holder and the bottom plate    -->
<!-- Created by Stefan -->
<!-- Service Robotics Group - Bulgaria -  Version 1.0 from Oct. 1th, 2018. -->


  <xacro:macro name="robco_2wd_base" >
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->

<link name="base_footprint">
  <!--base link should not have inertia!!!because of moveit and gazebo!-->
  <!--
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
              iyy="0.0001" iyz="0.0"
              izz="0.0001" />
    </inertial>
    -->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
      <material name="red" />
    </visual>

    <collision>
      <origin xyz="0 0 0.017" rpy="0 0 0" />
      <geometry>
       <box size="0.001 0.001 0.001" />
      </geometry>
    </collision>

</link>

    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

  <!-- JOINT BASE_LINK TO BASE_FRAME-->
  <joint name="base_footprint_base_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${base_plate_botom_from_base_frame_Z_offset}"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

<!-- BASE-LINK -->
  <!--Center on the bottom side of the base plate of the robot-->

 <link name="base_link">
   <pose>0 0 0.1 0 0 0</pose>

   <inertial>
      <origin xyz="0.0 0 ${round_plate_half_height}" rpy=" 0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name="collision">
    <origin xyz="0 0 ${round_plate_half_height}" rpy="0 0 0" />
      <geometry>
       <cylinder radius="${round_plate_radius}" length="${round_plate_height}"/>
      </geometry>
    </collision>

    <visual name="base_visual">
      <!--<origin xyz="0 0 ${round_plate_half_height}" rpy="0 0 0" />      -->
      <origin xyz="0 0 0" rpy="${ROTATE_90_DEGREES} 0 ${ROTATE_90_DEGREES}"/>
      <geometry>
        <!--<cylinder radius="${round_plate_radius}" length="${round_plate_height}"/>-->
        <mesh filename="package://robot_description/meshes/Eddiebot/ArloBottomplateTST.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <!--<material name="orange"/>-->
    </visual>

  </link>


<!--###########  DRIVE WHEELS #############################-->

<!--########### left wheel #############################-->
  <link name="left_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${ROTATE_90_DEGREES} ${ROTATE_90_DEGREES}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <!--<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>-->
      <origin xyz="0 0 0" rpy="0 ${2*ROTATE_90_DEGREES} ${ROTATE_90_DEGREES}"/>
      <geometry>
        <mesh filename="package://robot_description/meshes/Eddiebot/wheel.dae" scale="0.0012 0.0012 0.0012"/>
        <!--<cylinder radius="${wheel_radius}" length="${wheel_width}"/>-->
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${ROTATE_90_DEGREES} ${ROTATE_90_DEGREES}"/>
      <mass value="5"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="0 ${base_y_origin_to_wheel_origin} ${base_z_origin_to_wheel_origin}" rpy="0 0 0"/>
        <!--<origin xyz="0 0.19 -${0.10 - 0.0231}" rpy="0 0 0"/>-->
    <child link="left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

<!--########### right wheel #############################-->
  <link name="right_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${ROTATE_90_DEGREES} ${ROTATE_90_DEGREES}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <!--<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>-->
      <origin xyz="0 0 0" rpy="0 0 ${ROTATE_90_DEGREES}"/>
      <geometry>
        <mesh filename="package://robot_description/meshes/Eddiebot/wheel.dae" scale="0.0012 0.0012 0.0012"/>
        <!--<cylinder radius="${wheel_radius}" length="${wheel_width}"/>-->
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${ROTATE_90_DEGREES} ${ROTATE_90_DEGREES}"/>
      <mass value="5"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="0 -${base_y_origin_to_wheel_origin} ${base_z_origin_to_wheel_origin}" rpy="0 0 0"/>
    <!--<origin xyz="0 -0.19 -0.0231" rpy="0 0 0"/>-->
    <child link="right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

<!--########################################-->

<!--###########  CASTER WHEELS #############################-->

<!--########### caster front #############################-->
  <link name="caster_box_front">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${caster_box_lenght/2} ${caster_box_width/2} ${caster_box_height}"/>
      </geometry>
    </collision>
    <!--NO VISUAL FOR NOW    ->       TODO: CREATE MESH FOR THE CASTER WHEEL-->
    <!--<visual name="caster_box_front_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${caster_box_lenght/2} ${caster_box_width/2} ${caster_box_height}"/>
      </geometry>
       <material name="black"/>
    </visual>-->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

    <!-- JOINT caster_box_front TO base_link-->
  <joint name="base_caster_box_front_joint" type="fixed">
    <!-- NB: Z goes to - as we are below bottom deck(base) -->
    <origin rpy="0 0 0" xyz="${caster_X_offset_from_base_link} 0 -${caster_box_height/2}"/>
    <parent link="base_link"/>
    <child link="caster_box_front"/>
  </joint>

     <!--********caster sphere front*********************-->
    <link name="caster_sphere_front">
        <collision name="collision">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_sphere_radius}"/>
            </geometry>
        </collision>
        <!--NO VISUAL FOR NOW    ->       TODO: CREATE MESH FOR THE CASTER WHEEL-->
        <!--<visual name="caster_sphere_front_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_sphere_radius}"/>
      </geometry>
      <material name="black"/>
        </visual>-->
        <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
        </inertial>
    </link>

    <!-- JOINT caster_sphere_front TO caster_box_front-->
  <joint name="caster_box_front_caster_sphere_front_joint" type="fixed">
    <!-- NB: Z goes to - as we are below bottom deck(base)-->
    <origin rpy="0 0 0" xyz="0 0 -${caster_box_height/2 + caster_sphere_radius}"/>
    <parent link="caster_box_front"/>
    <child link="caster_sphere_front"/>
  </joint>

<!--########### caster back #############################-->
  <link name="caster_box_back">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${caster_box_lenght/2} ${caster_box_width/2} ${caster_box_height}"/>
      </geometry>
    </collision>
    <!--NO VISUAL FOR NOW    ->       TODO: CREATE MESH FOR THE CASTER WHEEL-->
    <!--<visual name="caster_box_front_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${caster_box_lenght/2} ${caster_box_width/2} ${caster_box_height}"/>
      </geometry>
       <material name="black"/>
    </visual>-->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

    <!-- JOINT caster_box_back TO base_link-->
  <joint name="base_caster_box_back_joint" type="fixed">
     <!-- NB: Z goes to - as we are below bottom deck(base) -->
    <origin rpy="0 0 0" xyz="-${caster_X_offset_from_base_link} 0 -${caster_box_height/2}"/>
    <parent link="base_link"/>
    <child link="caster_box_back"/>
  </joint>

     <!--*********caster sphere back********************-->
    <link name="caster_sphere_back">
        <collision name="collision">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <sphere radius="${caster_sphere_radius}"/>
            </geometry>
        </collision>
        <!--NO VISUAL FOR NOW    ->       TODO: CREATE MESH FOR THE CASTER WHEEL-->
        <!--<visual name="caster_sphere_front_visual">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_sphere_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>-->
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.15"/>
            <inertia
                ixx=".1" ixy="0.0" ixz="0.0"
                iyy=".1" iyz="0.0"
                izz=".1"/>
        </inertial>
    </link>

    <!-- JOINT caster_sphere_back TO caster_box_back-->
  <joint name="caster_box_back_caster_sphere_back_joint" type="fixed">
    <!-- NB: Z goes to - as we are below bottom deck(base)-->
    <origin rpy="0 0 0" xyz="0 0 -${caster_box_height/2 + caster_sphere_radius}"/>
    <parent link="caster_box_back"/>
    <child link="caster_sphere_back"/>
  </joint>

  </xacro:macro>

</robot>